services:
  rabbitmq:
    image: rabbitmq:4-management
    container_name: thi-rabbitmq
    restart: always
    ports:
      - "5672:5672"   # AMQP port
      - "15672:15672" # Management UI port
    volumes:
      - rabbitmq-lib:/var/lib/rabbitmq/
      - rabbitmq-log:/var/log/rabbitmq

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: thi-backend
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app
    environment:
      - HOST=${HOST}
      - PORT=${PORT}
      - DBNAME=${DBNAME}
      - ORIGIN_URL=${ORIGIN_URL}
      - broker_url=amqp://guest:guest@rabbitmq:5672/
      - STORAGE_URL=${STORAGE_URL}
      - STORAGE_KEY=${STORAGE_KEY}
    depends_on:
      - rabbitmq
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
  
  celery_worker:
    build: 
      context: ./server
      dockerfile: Dockerfile
    container_name: thi-celery-worker
    volumes:
      - ./server:/app
    environment:
      - HOST=${HOST}
      - PORT=${PORT}
      - DBNAME=${DBNAME}
      - ORIGIN_URL=${ORIGIN_URL}
      - broker_url=amqp://guest:guest@rabbitmq:5672/
    depends_on:
      - rabbitmq
    command: celery -A celery_task.app worker --loglevel=info

volumes:
  rabbitmq-lib:
    driver: local
  rabbitmq-log:
    driver: local

