# [destination.postgres.credentials]
# database = "postgres"
# username = "postgres"
# password = "password"
# host = "localhost"
# port = 5433
# connect_timeout = 15

# TODO: Replace with actual database credentials